[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.package]
edition = "2024"

[workspace.lints.clippy]
explicit_counter_loop = "allow"
new_without_default = "allow"

[workspace.dependencies]
bytes_ext = { path = "crates/bytes_ext" }
clap = "4.5.38"
cpal = "0.18"
num = "0.4.3"
nuked_opl3 = { path = "crates/nuked_opl3" }
png = "0.18"
rand = { version = "0.9.2" }
