use crate::GameState;

// = the seg001 locations[] addressing: the table starts at seg001:0100 and
// each record is 0x1c bytes. Several DOS-side words (data_046fc,
// current_location_ptr, ...) hold a record's ds pointer; the port keeps those
// words in the same encoding so the 0/0xffff/0xfff0.. sentinels stay apart
// from real locations, and converts at the accesses.
pub(crate) const LOCATION_PTR_BASE: u16 = 0x100;
pub(crate) const LOCATION_RECORD_SIZE: u16 = 0x1c;

pub(crate) fn location_ptr(index: u16) -> u16 {
    LOCATION_PTR_BASE + LOCATION_RECORD_SIZE * index
}

// = the inverse of location_index_from_ptr: a locations[] index back into
// the DOS record-pointer encoding.
pub(crate) fn location_ptr_from_index(index: usize) -> u16 {
    LOCATION_PTR_BASE + index as u16 * LOCATION_RECORD_SIZE
}

pub(crate) fn location_index_from_ptr(ptr: u16) -> usize {
    ((ptr - LOCATION_PTR_BASE) / LOCATION_RECORD_SIZE) as usize
}

#[derive(Debug, Default, Clone, Copy)]
pub struct Equipment {
    pub harvesters: u8,
    pub ornithopters: u8,
    pub krys_knives: u8,
    pub laser_guns: u8,
    pub weirding_modules: u8,
    pub atomics: u8,
    pub bulbs: u8,
}

impl Equipment {
    // = the DOS equipment row layout (Location +0x14..+0x1a and the
    // seg001:46fe availability buffer): slot 0 = harvesters .. 6 = bulbs,
    // for the sites that index the row by slot number.
    pub(crate) fn slot(&self, slot: usize) -> u8 {
        *[
            &self.harvesters,
            &self.ornithopters,
            &self.krys_knives,
            &self.laser_guns,
            &self.weirding_modules,
            &self.atomics,
            &self.bulbs,
        ][slot]
    }

    pub(crate) fn slot_mut(&mut self, slot: usize) -> &mut u8 {
        [
            &mut self.harvesters,
            &mut self.ornithopters,
            &mut self.krys_knives,
            &mut self.laser_guns,
            &mut self.weirding_modules,
            &mut self.atomics,
            &mut self.bulbs,
        ]
        .into_iter()
        .nth(slot)
        .unwrap()
    }
}

#[derive(Clone, Copy)]
pub struct Location {
    pub first_name: u8,
    pub last_name: u8,
    pub map_x: i16,
    pub map_y: i16,
    // = Location.map_offset (offset +6) — the cached MAP.HSQ byte offset of
    // the location's map cell, filled by init_location_map_offsets (the DOS
    // startup loop at seg000:019e); find_location_by_map_offset matches the
    // desert-walk arrival cell against it.
    pub map_offset: u16,
    pub appearance: u8,
    pub troop_id: u8,
    pub status: u8,
    pub discoverable_at_phase: i8,
    pub field_c: u16,
    pub field_e: u16,
    pub spice_field_id: u8,
    pub spice_amount: u8,
    pub spice_density: u8,
    pub field_13: u8,
    pub equipment: Equipment,
    pub water: u8,
}

// = seg001:0100 locations[].first_name / last_name — the two halves of a
// location's display name.
const FIRST_NAME_ARRAKEEN: u8 = 1;
const FIRST_NAME_CARTHAG: u8 = 2;
const FIRST_NAME_TUONO: u8 = 3;
const FIRST_NAME_HABBANYA: u8 = 4;
const FIRST_NAME_OXTYN: u8 = 5;
const FIRST_NAME_TSYMPO: u8 = 6;
const FIRST_NAME_BLEDAN: u8 = 7;
const FIRST_NAME_ERGSUN: u8 = 8;
const FIRST_NAME_HAGA: u8 = 9;
const FIRST_NAME_CIELAGO: u8 = 10;
const FIRST_NAME_SIHAYA: u8 = 11;
const FIRST_NAME_CELIMYN: u8 = 12;

const LAST_NAME_ATREIDES: u8 = 1;
const LAST_NAME_HARKONNEN: u8 = 2;
const LAST_NAME_TABR: u8 = 3;
const LAST_NAME_TIMIN: u8 = 4;
const LAST_NAME_TUEK: u8 = 5;
const LAST_NAME_HARG: u8 = 6;
const LAST_NAME_CLAM: u8 = 7;
const LAST_NAME_TSYMYN: u8 = 8;
const LAST_NAME_SIET: u8 = 9;
const LAST_NAME_PYONS: u8 = 10;
const LAST_NAME_PYORT: u8 = 11;

// = seg001:0100 locations — the 70-entry location table's static initializer.
pub(crate) const LOCATIONS: [Location; 70] = [
    // [0] Carthag-Atreides
    Location {
        first_name: FIRST_NAME_CARTHAG,
        last_name: LAST_NAME_ATREIDES,
        map_x: 6421,
        map_y: -4,
        map_offset: 0,
        appearance: 0x20,
        troop_id: 0,
        status: 0b00010000,
        discoverable_at_phase: -1,
        field_c: 0,
        field_e: 0,
        spice_field_id: 0,
        spice_amount: 0,
        spice_density: 0,
        field_13: 0,
        equipment: Equipment {
            harvesters: 0,
            ornithopters: 0,
            krys_knives: 0,
            laser_guns: 0,
            weirding_modules: 0,
            atomics: 0,
            bulbs: 0,
        },
        water: 0,
    },
    // [1] Arrakeen-Harkonnen
    Location {
        first_name: FIRST_NAME_ARRAKEEN,
        last_name: LAST_NAME_HARKONNEN,
        map_x: 15000,
        map_y: -62,
        map_offset: 0,
        appearance: 0x30,
        troop_id: 0x43,
        status: 0b00000000,
        discoverable_at_phase: -1,
        field_c: 0,
        field_e: 0,
        spice_field_id: 0,
        spice_amount: 0,
        spice_density: 0,
        field_13: 0,
        equipment: Equipment {
            harvesters: 0,
            ornithopters: 0,
            krys_knives: 1,
            laser_guns: 1,
            weirding_modules: 1,
            atomics: 0,
            bulbs: 0,
        },
        water: 0,
    },
    // [2] Arrakeen-Tabr
    Location {
        first_name: FIRST_NAME_ARRAKEEN,
        last_name: LAST_NAME_TABR,
        map_x: 11006,
        map_y: -54,
        map_offset: 0,
        appearance: 0x28,
        troop_id: 0x29,
        status: 0b10000000,
        discoverable_at_phase: -1,
        field_c: 0,
        field_e: 0,
        spice_field_id: 0,
        spice_amount: 0,
        spice_density: 0x78,
        field_13: 0,
        equipment: Equipment {
            harvesters: 2,
            ornithopters: 2,
            krys_knives: 3,
            laser_guns: 3,
            weirding_modules: 3,
            atomics: 3,
            bulbs: 0,
        },
        water: 0,
    },
    // [3] Arrakeen-Timin
    Location {
        first_name: FIRST_NAME_ARRAKEEN,
        last_name: LAST_NAME_TIMIN,
        map_x: 15901,
        map_y: -48,
        map_offset: 0,
        appearance: 0x2b,
        troop_id: 0x1e,
        status: 0b10000000,
        discoverable_at_phase: -1,
        field_c: 0,
        field_e: 0,
        spice_field_id: 0,
        spice_amount: 0,
        spice_density: 0x64,
        field_13: 0,
        equipment: Equipment {
            harvesters: 2,
            ornithopters: 3,
            krys_knives: 3,
            laser_guns: 3,
            weirding_modules: 3,
            atomics: 3,
            bulbs: 0,
        },
        water: 0,
    },
    // [4] Arrakeen-Tuek
    Location {
        first_name: FIRST_NAME_ARRAKEEN,
        last_name: LAST_NAME_TUEK,
        map_x: 10158,
        map_y: -67,
        map_offset: 0,
        appearance: 0x29,
        troop_id: 0x35,
        status: 0b10000000,
        discoverable_at_phase: -1,
        field_c: 0,
        field_e: 0,
        spice_field_id: 0,
        spice_amount: 0,
        spice_density: 0x7d,
        field_13: 0,
        equipment: Equipment {
            harvesters: 1,
            ornithopters: 2,
            krys_knives: 0,
            laser_guns: 1,
            weirding_modules: 1,
            atomics: 1,
            bulbs: 0,
        },
        water: 0,
    },
    // [5] Arrakeen-Harg
    Location {
        first_name: FIRST_NAME_ARRAKEEN,
        last_name: LAST_NAME_HARG,
        map_x: 6967,
        map_y: -32,
        map_offset: 0,
        appearance: 0x2d,
        troop_id: 0x24,
        status: 0b10000000,
        discoverable_at_phase: -1,
        field_c: 0,
        field_e: 0,
        spice_field_id: 0,
        spice_amount: 0,
        spice_density: 0xc8,
        field_13: 0,
        equipment: Equipment {
            harvesters: 2,
            ornithopters: 2,
            krys_knives: 0,
            laser_guns: 3,
            weirding_modules: 1,
            atomics: 1,
            bulbs: 0,
        },
        water: 0,
    },
    // [6] Arrakeen-Clam
    Location {
        first_name: FIRST_NAME_ARRAKEEN,
        last_name: LAST_NAME_CLAM,
        map_x: 9936,
        map_y: -43,
        map_offset: 0,
        appearance: 0x2c,
        troop_id: 0x21,
        status: 0b10000000,
        discoverable_at_phase: -1,
        field_c: 0,
        field_e: 0,
        spice_field_id: 0,
        spice_amount: 0,
        spice_density: 0xb4,
        field_13: 0,
        equipment: Equipment {
            harvesters: 2,
            ornithopters: 3,
            krys_knives: 3,
            laser_guns: 3,
            weirding_modules: 2,
            atomics: 0,
            bulbs: 0,
        },
        water: 0,
    },
    // [7] Arrakeen-Tsymyn
    Location {
        first_name: FIRST_NAME_ARRAKEEN,
        last_name: LAST_NAME_TSYMYN,
        map_x: 13068,
        map_y: -39,
        map_offset: 0,
        appearance: 0x2e,
        troop_id: 0x1b,
        status: 0b10000000,
        discoverable_at_phase: -1,
        field_c: 0,
        field_e: 0,
        spice_field_id: 0,
        spice_amount: 0,
        spice_density: 0x2d,
        field_13: 0,
        equipment: Equipment {
            harvesters: 2,
            ornithopters: 2,
            krys_knives: 3,
            laser_guns: 3,
            weirding_modules: 3,
            atomics: 0,
            bulbs: 0,
        },
        water: 0,
    },
    // [8] Arrakeen-Siet
    Location {
        first_name: FIRST_NAME_ARRAKEEN,
        last_name: LAST_NAME_SIET,
        map_x: 5769,
        map_y: -49,
        map_offset: 0,
        appearance: 0x2a,
        troop_id: 0x27,
        status: 0b10000000,
        discoverable_at_phase: -1,
        field_c: 0,
        field_e: 0,
        spice_field_id: 0,
        spice_amount: 0,
        spice_density: 0x8c,
        field_13: 0,
        equipment: Equipment {
            harvesters: 2,
            ornithopters: 2,
            krys_knives: 0,
            laser_guns: 2,
            weirding_modules: 2,
            atomics: 0,
            bulbs: 0,
        },
        water: 0,
    },
    // [9] Arrakeen-Pyons
    Location {
        first_name: FIRST_NAME_ARRAKEEN,
        last_name: LAST_NAME_PYONS,
        map_x: 15385,
        map_y: -40,
        map_offset: 0,
        appearance: 0x21,
        troop_id: 0,
        status: 0b10000000,
        discoverable_at_phase: 80,
        field_c: 0,
        field_e: 0,
        spice_field_id: 0,
        spice_amount: 0,
        spice_density: 0,
        field_13: 0,
        equipment: Equipment {
            harvesters: 0,
            ornithopters: 0,
            krys_knives: 0,
            laser_guns: 0,
            weirding_modules: 0,
            atomics: 0,
            bulbs: 0,
        },
        water: 0,
    },
    // [10] Carthag-Tabr
    Location {
        first_name: FIRST_NAME_CARTHAG,
        last_name: LAST_NAME_TABR,
        map_x: 12616,
        map_y: -21,
        map_offset: 0,
        appearance: 2,
        troop_id: 8,
        status: 0b10000000,
        discoverable_at_phase: 4,
        field_c: 0,
        field_e: 0,
        spice_field_id: 0,
        spice_amount: 0,
        spice_density: 0x78,
        field_13: 0,
        equipment: Equipment {
            harvesters: 0,
            ornithopters: 0,
            krys_knives: 0,
            laser_guns: 0,
            weirding_modules: 0,
            atomics: 0,
            bulbs: 0,
        },
        water: 0,
    },
    // [11] Carthag-Timin
    Location {
        first_name: FIRST_NAME_CARTHAG,
        last_name: LAST_NAME_TIMIN,
        map_x: 9550,
        map_y: -4,
        map_offset: 0,
        appearance: 1,
        troop_id: 3,
        status: 0b01000000,
        discoverable_at_phase: 0,
        field_c: 0,
        field_e: 0,
        spice_field_id: 0,
        spice_amount: 0,
        spice_density: 0x3c,
        field_13: 0,
        equipment: Equipment {
            harvesters: 0,
            ornithopters: 0,
            krys_knives: 0,
            laser_guns: 0,
            weirding_modules: 0,
            atomics: 0,
            bulbs: 0,
        },
        water: 0,
    },
    // [12] Carthag-Tuek
    Location {
        first_name: FIRST_NAME_CARTHAG,
        last_name: LAST_NAME_TUEK,
        map_x: 9800,
        map_y: 10,
        map_offset: 0,
        appearance: 0,
        troop_id: 1,
        status: 0b01000000,
        discoverable_at_phase: 0,
        field_c: 0,
        field_e: 0,
        spice_field_id: 0,
        spice_amount: 0,
        spice_density: 0x54,
        field_13: 0,
        equipment: Equipment {
            harvesters: 0,
            ornithopters: 0,
            krys_knives: 0,
            laser_guns: 0,
            weirding_modules: 0,
            atomics: 0,
            bulbs: 0,
        },
        water: 0,
    },
    // [13] Carthag-Harg
    Location {
        first_name: FIRST_NAME_CARTHAG,
        last_name: LAST_NAME_HARG,
        map_x: 8478,
        map_y: -19,
        map_offset: 0,
        appearance: 3,
        troop_id: 2,
        status: 0b01000000,
        discoverable_at_phase: 0,
        field_c: 0,
        field_e: 0,
        spice_field_id: 0,
        spice_amount: 0,
        spice_density: 0x2d,
        field_13: 0,
        equipment: Equipment {
            harvesters: 0,
            ornithopters: 0,
            krys_knives: 0,
            laser_guns: 0,
            weirding_modules: 0,
            atomics: 0,
            bulbs: 0,
        },
        water: 0,
    },
    // [14] Carthag-Clam
    Location {
        first_name: FIRST_NAME_CARTHAG,
        last_name: LAST_NAME_CLAM,
        map_x: 4400,
        map_y: 6,
        map_offset: 0,
        appearance: 0,
        troop_id: 0,
        status: 0b10000000,
        discoverable_at_phase: 60,
        field_c: 0,
        field_e: 0,
        spice_field_id: 0,
        spice_amount: 0,
        spice_density: 0x8c,
        field_13: 0,
        equipment: Equipment {
            harvesters: 1,
            ornithopters: 1,
            krys_knives: 0,
            laser_guns: 0,
            weirding_modules: 0,
            atomics: 0,
            bulbs: 0,
        },
        water: 0x0a,
    },
    // [15] Tuono-Tabr
    Location {
        first_name: FIRST_NAME_TUONO,
        last_name: LAST_NAME_TABR,
        map_x: 13000,
        map_y: 8,
        map_offset: 0,
        appearance: 8,
        troop_id: 5,
        status: 0b11100000,
        discoverable_at_phase: 2,
        field_c: 0,
        field_e: 0,
        spice_field_id: 0,
        spice_amount: 0,
        spice_density: 0x63,
        field_13: 0,
        equipment: Equipment {
            harvesters: 1,
            ornithopters: 0,
            krys_knives: 0,
            laser_guns: 0,
            weirding_modules: 0,
            atomics: 0,
            bulbs: 0,
        },
        water: 0x14,
    },
    // [16] Tuono-Timin
    Location {
        first_name: FIRST_NAME_TUONO,
        last_name: LAST_NAME_TIMIN,
        map_x: 15770,
        map_y: 22,
        map_offset: 0,
        appearance: 7,
        troop_id: 0,
        status: 0b10000000,
        discoverable_at_phase: 17,
        field_c: 0,
        field_e: 0,
        spice_field_id: 0,
        spice_amount: 0,
        spice_density: 0xa0,
        field_13: 0,
        equipment: Equipment {
            harvesters: 1,
            ornithopters: 0,
            krys_knives: 0,
            laser_guns: 0,
            weirding_modules: 0,
            atomics: 0,
            bulbs: 0,
        },
        water: 0,
    },
    // [17] Tuono-Tuek
    Location {
        first_name: FIRST_NAME_TUONO,
        last_name: LAST_NAME_TUEK,
        map_x: 19759,
        map_y: -4,
        map_offset: 0,
        appearance: 4,
        troop_id: 9,
        status: 0b10000000,
        discoverable_at_phase: 4,
        field_c: 0,
        field_e: 0,
        spice_field_id: 0,
        spice_amount: 0,
        spice_density: 0xb4,
        field_13: 0,
        equipment: Equipment {
            harvesters: 0,
            ornithopters: 0,
            krys_knives: 0,
            laser_guns: 0,
            weirding_modules: 0,
            atomics: 0,
            bulbs: 0,
        },
        water: 0,
    },
    // [18] Tuono-Harg
    Location {
        first_name: FIRST_NAME_TUONO,
        last_name: LAST_NAME_HARG,
        map_x: 15700,
        map_y: -17,
        map_offset: 0,
        appearance: 3,
        troop_id: 0,
        status: 0b10000000,
        discoverable_at_phase: 12,
        field_c: 0,
        field_e: 0,
        spice_field_id: 0,
        spice_amount: 0,
        spice_density: 0xa0,
        field_13: 0,
        equipment: Equipment {
            harvesters: 2,
            ornithopters: 0,
            krys_knives: 0,
            laser_guns: 0,
            weirding_modules: 0,
            atomics: 0,
            bulbs: 0,
        },
        water: 0,
    },
    // [19] Tuono-Clam
    Location {
        first_name: FIRST_NAME_TUONO,
        last_name: LAST_NAME_CLAM,
        map_x: 18040,
        map_y: 8,
        map_offset: 0,
        appearance: 6,
        troop_id: 0,
        status: 0b10000000,
        discoverable_at_phase: 16,
        field_c: 0,
        field_e: 0,
        spice_field_id: 0,
        spice_amount: 0,
        spice_density: 0xd2,
        field_13: 0,
        equipment: Equipment {
            harvesters: 1,
            ornithopters: 2,
            krys_knives: 3,
            laser_guns: 0,
            weirding_modules: 0,
            atomics: 0,
            bulbs: 0,
        },
        water: 0,
    },
    // [20] Tuono-Pyons
    Location {
        first_name: FIRST_NAME_TUONO,
        last_name: LAST_NAME_PYONS,
        map_x: 20600,
        map_y: 15,
        map_offset: 0,
        appearance: 0x21,
        troop_id: 0,
        status: 0b10000000,
        discoverable_at_phase: 56,
        field_c: 0,
        field_e: 0,
        spice_field_id: 0,
        spice_amount: 0,
        spice_density: 0,
        field_13: 0,
        equipment: Equipment {
            harvesters: 0,
            ornithopters: 0,
            krys_knives: 0,
            laser_guns: 0,
            weirding_modules: 0,
            atomics: 0,
            bulbs: 0,
        },
        water: 0,
    },
    // [21] Habbanya-Tabr
    Location {
        first_name: FIRST_NAME_HABBANYA,
        last_name: LAST_NAME_TABR,
        map_x: 12743,
        map_y: 48,
        map_offset: 0,
        appearance: 5,
        troop_id: 7,
        status: 0b10000000,
        discoverable_at_phase: 20,
        field_c: 0,
        field_e: 0,
        spice_field_id: 0,
        spice_amount: 0,
        spice_density: 0xc8,
        field_13: 0,
        equipment: Equipment {
            harvesters: 1,
            ornithopters: 0,
            krys_knives: 0,
            laser_guns: 0,
            weirding_modules: 0,
            atomics: 0,
            bulbs: 0,
        },
        water: 0,
    },
    // [22] Habbanya-Timin
    Location {
        first_name: FIRST_NAME_HABBANYA,
        last_name: LAST_NAME_TIMIN,
        map_x: 11405,
        map_y: 24,
        map_offset: 0,
        appearance: 4,
        troop_id: 4,
        status: 0b10000000,
        discoverable_at_phase: 20,
        field_c: 0,
        field_e: 0,
        spice_field_id: 0,
        spice_amount: 0,
        spice_density: 0xaa,
        field_13: 0,
        equipment: Equipment {
            harvesters: 0,
            ornithopters: 0,
            krys_knives: 0,
            laser_guns: 0,
            weirding_modules: 0,
            atomics: 0,
            bulbs: 0,
        },
        water: 0,
    },
    // [23] Habbanya-Tuek
    Location {
        first_name: FIRST_NAME_HABBANYA,
        last_name: LAST_NAME_TUEK,
        map_x: 12721,
        map_y: 35,
        map_offset: 0,
        appearance: 7,
        troop_id: 6,
        status: 0b10000000,
        discoverable_at_phase: 20,
        field_c: 0,
        field_e: 0,
        spice_field_id: 0,
        spice_amount: 0,
        spice_density: 0xf0,
        field_13: 0,
        equipment: Equipment {
            harvesters: 0,
            ornithopters: 0,
            krys_knives: 0,
            laser_guns: 0,
            weirding_modules: 0,
            atomics: 0,
            bulbs: 0,
        },
        water: 0,
    },
    // [24] Habbanya-Clam
    Location {
        first_name: FIRST_NAME_HABBANYA,
        last_name: LAST_NAME_CLAM,
        map_x: 5800,
        map_y: 27,
        map_offset: 0,
        appearance: 3,
        troop_id: 0,
        status: 0b10000000,
        discoverable_at_phase: 22,
        field_c: 0,
        field_e: 0,
        spice_field_id: 0,
        spice_amount: 0,
        spice_density: 0xc8,
        field_13: 0,
        equipment: Equipment {
            harvesters: 1,
            ornithopters: 3,
            krys_knives: 0,
            laser_guns: 1,
            weirding_modules: 0,
            atomics: 0,
            bulbs: 0,
        },
        water: 0,
    },
    // [25] Habbanya-Harg
    Location {
        first_name: FIRST_NAME_HABBANYA,
        last_name: LAST_NAME_HARG,
        map_x: 4049,
        map_y: 70,
        map_offset: 0,
        appearance: 9,
        troop_id: 0x0a,
        status: 0b10100000,
        discoverable_at_phase: 72,
        field_c: 0,
        field_e: 0,
        spice_field_id: 0,
        spice_amount: 0,
        spice_density: 0xf0,
        field_13: 0,
        equipment: Equipment {
            harvesters: 1,
            ornithopters: 0,
            krys_knives: 0,
            laser_guns: 0,
            weirding_modules: 0,
            atomics: 0,
            bulbs: 0,
        },
        water: 0xc8,
    },
    // [26] Oxtyn-Tabr
    Location {
        first_name: FIRST_NAME_OXTYN,
        last_name: LAST_NAME_TABR,
        map_x: -8457,
        map_y: 23,
        map_offset: 0,
        appearance: 5,
        troop_id: 0,
        status: 0b10000000,
        discoverable_at_phase: 68,
        field_c: 0,
        field_e: 0,
        spice_field_id: 0,
        spice_amount: 0,
        spice_density: 0xb4,
        field_13: 0,
        equipment: Equipment {
            harvesters: 2,
            ornithopters: 1,
            krys_knives: 1,
            laser_guns: 0,
            weirding_modules: 0,
            atomics: 0,
            bulbs: 0,
        },
        water: 0,
    },
    // [27] Oxtyn-Timin
    Location {
        first_name: FIRST_NAME_OXTYN,
        last_name: LAST_NAME_TIMIN,
        map_x: -2222,
        map_y: 30,
        map_offset: 0,
        appearance: 2,
        troop_id: 0x0b,
        status: 0b10000000,
        discoverable_at_phase: 72,
        field_c: 0,
        field_e: 0,
        spice_field_id: 0,
        spice_amount: 0,
        spice_density: 0xa0,
        field_13: 0,
        equipment: Equipment {
            harvesters: 1,
            ornithopters: 0,
            krys_knives: 0,
            laser_guns: 0,
            weirding_modules: 0,
            atomics: 0,
            bulbs: 0,
        },
        water: 0,
    },
    // [28] Oxtyn-Tuek
    Location {
        first_name: FIRST_NAME_OXTYN,
        last_name: LAST_NAME_TUEK,
        map_x: -6454,
        map_y: 10,
        map_offset: 0,
        appearance: 5,
        troop_id: 0x0c,
        status: 0b10000000,
        discoverable_at_phase: 72,
        field_c: 0,
        field_e: 0,
        spice_field_id: 0,
        spice_amount: 0,
        spice_density: 0x64,
        field_13: 0,
        equipment: Equipment {
            harvesters: 0,
            ornithopters: 1,
            krys_knives: 1,
            laser_guns: 0,
            weirding_modules: 0,
            atomics: 0,
            bulbs: 0,
        },
        water: 0,
    },
    // [29] Oxtyn-Harg
    Location {
        first_name: FIRST_NAME_OXTYN,
        last_name: LAST_NAME_HARG,
        map_x: 670,
        map_y: 13,
        map_offset: 0,
        appearance: 7,
        troop_id: 0,
        status: 0b10000000,
        discoverable_at_phase: 40,
        field_c: 0,
        field_e: 0,
        spice_field_id: 0,
        spice_amount: 0,
        spice_density: 0xfa,
        field_13: 0,
        equipment: Equipment {
            harvesters: 1,
            ornithopters: 1,
            krys_knives: 5,
            laser_guns: 0,
            weirding_modules: 0,
            atomics: 0,
            bulbs: 0,
        },
        water: 0,
    },
    // [30] Oxtyn-Pyons
    Location {
        first_name: FIRST_NAME_OXTYN,
        last_name: LAST_NAME_PYONS,
        map_x: 4213,
        map_y: 18,
        map_offset: 0,
        appearance: 0x21,
        troop_id: 0,
        status: 0b10000000,
        discoverable_at_phase: 56,
        field_c: 0,
        field_e: 0,
        spice_field_id: 0,
        spice_amount: 0,
        spice_density: 0,
        field_13: 0,
        equipment: Equipment {
            harvesters: 0,
            ornithopters: 0,
            krys_knives: 0,
            laser_guns: 0,
            weirding_modules: 0,
            atomics: 0,
            bulbs: 0,
        },
        water: 0,
    },
    // [31] Tsympo-Tabr
    Location {
        first_name: FIRST_NAME_TSYMPO,
        last_name: LAST_NAME_TABR,
        map_x: 2035,
        map_y: -40,
        map_offset: 0,
        appearance: 0x28,
        troop_id: 0x2c,
        status: 0b10000000,
        discoverable_at_phase: -1,
        field_c: 0,
        field_e: 0,
        spice_field_id: 0,
        spice_amount: 0,
        spice_density: 0x96,
        field_13: 0,
        equipment: Equipment {
            harvesters: 2,
            ornithopters: 3,
            krys_knives: 0,
            laser_guns: 3,
            weirding_modules: 0,
            atomics: 0,
            bulbs: 0,
        },
        water: 0,
    },
    // [32] Tsympo-Timin
    Location {
        first_name: FIRST_NAME_TSYMPO,
        last_name: LAST_NAME_TIMIN,
        map_x: -3856,
        map_y: -35,
        map_offset: 0,
        appearance: 0x29,
        troop_id: 0x2f,
        status: 0b10000000,
        discoverable_at_phase: -1,
        field_c: 0,
        field_e: 0,
        spice_field_id: 0,
        spice_amount: 0,
        spice_density: 0x20,
        field_13: 0,
        equipment: Equipment {
            harvesters: 1,
            ornithopters: 0,
            krys_knives: 3,
            laser_guns: 3,
            weirding_modules: 0,
            atomics: 0,
            bulbs: 0,
        },
        water: 0,
    },
    // [33] Tsympo-Tuek
    Location {
        first_name: FIRST_NAME_TSYMPO,
        last_name: LAST_NAME_TUEK,
        map_x: 1787,
        map_y: -21,
        map_offset: 0,
        appearance: 1,
        troop_id: 0,
        status: 0b10000000,
        discoverable_at_phase: 80,
        field_c: 0,
        field_e: 0,
        spice_field_id: 0,
        spice_amount: 0,
        spice_density: 0x82,
        field_13: 0,
        equipment: Equipment {
            harvesters: 1,
            ornithopters: 0,
            krys_knives: 1,
            laser_guns: 0,
            weirding_modules: 0,
            atomics: 0,
            bulbs: 0,
        },
        water: 0,
    },
    // [34] Tsympo-Harg
    Location {
        first_name: FIRST_NAME_TSYMPO,
        last_name: LAST_NAME_HARG,
        map_x: -7641,
        map_y: -16,
        map_offset: 0,
        appearance: 0,
        troop_id: 0x0d,
        status: 0b10000000,
        discoverable_at_phase: 80,
        field_c: 0,
        field_e: 0,
        spice_field_id: 0,
        spice_amount: 0,
        spice_density: 0x78,
        field_13: 0,
        equipment: Equipment {
            harvesters: 0,
            ornithopters: 0,
            krys_knives: 1,
            laser_guns: 0,
            weirding_modules: 0,
            atomics: 0,
            bulbs: 0,
        },
        water: 0,
    },
    // [35] Tsympo-Clam
    Location {
        first_name: FIRST_NAME_TSYMPO,
        last_name: LAST_NAME_CLAM,
        map_x: -1751,
        map_y: -54,
        map_offset: 0,
        appearance: 0x2a,
        troop_id: 0x32,
        status: 0b10000000,
        discoverable_at_phase: -1,
        field_c: 0,
        field_e: 0,
        spice_field_id: 0,
        spice_amount: 0,
        spice_density: 0xb4,
        field_13: 0,
        equipment: Equipment {
            harvesters: 2,
            ornithopters: 2,
            krys_knives: 2,
            laser_guns: 2,
            weirding_modules: 2,
            atomics: 0,
            bulbs: 0,
        },
        water: 0,
    },
    // [36] Tsympo-Tsymyn
    Location {
        first_name: FIRST_NAME_TSYMPO,
        last_name: LAST_NAME_TSYMYN,
        map_x: -2436,
        map_y: -21,
        map_offset: 0,
        appearance: 6,
        troop_id: 0,
        status: 0b10000000,
        discoverable_at_phase: 60,
        field_c: 0,
        field_e: 0,
        spice_field_id: 0,
        spice_amount: 0,
        spice_density: 0xb4,
        field_13: 0,
        equipment: Equipment {
            harvesters: 1,
            ornithopters: 1,
            krys_knives: 0,
            laser_guns: 2,
            weirding_modules: 1,
            atomics: 0,
            bulbs: 0,
        },
        water: 0,
    },
    // [37] Tsympo-Siet
    Location {
        first_name: FIRST_NAME_TSYMPO,
        last_name: LAST_NAME_SIET,
        map_x: 6214,
        map_y: -60,
        map_offset: 0,
        appearance: 0x2b,
        troop_id: 0x34,
        status: 0b10000000,
        discoverable_at_phase: -1,
        field_c: 0,
        field_e: 0,
        spice_field_id: 0,
        spice_amount: 0,
        spice_density: 0xd2,
        field_13: 0,
        equipment: Equipment {
            harvesters: 2,
            ornithopters: 2,
            krys_knives: 1,
            laser_guns: 1,
            weirding_modules: 1,
            atomics: 0,
            bulbs: 0,
        },
        water: 0,
    },
    // [38] Tsympo-Pyons
    Location {
        first_name: FIRST_NAME_TSYMPO,
        last_name: LAST_NAME_PYONS,
        map_x: -3793,
        map_y: -11,
        map_offset: 0,
        appearance: 0x21,
        troop_id: 0,
        status: 0b10000000,
        discoverable_at_phase: 71,
        field_c: 0,
        field_e: 0,
        spice_field_id: 0,
        spice_amount: 0,
        spice_density: 0,
        field_13: 0,
        equipment: Equipment {
            harvesters: 0,
            ornithopters: 0,
            krys_knives: 0,
            laser_guns: 0,
            weirding_modules: 0,
            atomics: 0,
            bulbs: 0,
        },
        water: 0,
    },
    // [39] Tsympo-Pyort
    Location {
        first_name: FIRST_NAME_TSYMPO,
        last_name: LAST_NAME_PYORT,
        map_x: 3276,
        map_y: -73,
        map_offset: 0,
        appearance: 0x2c,
        troop_id: 0x36,
        status: 0b10000000,
        discoverable_at_phase: -1,
        field_c: 0,
        field_e: 0,
        spice_field_id: 0,
        spice_amount: 0,
        spice_density: 0x78,
        field_13: 0,
        equipment: Equipment {
            harvesters: 0,
            ornithopters: 0,
            krys_knives: 1,
            laser_guns: 1,
            weirding_modules: 1,
            atomics: 0,
            bulbs: 0,
        },
        water: 0,
    },
    // [40] Bledan-Tabr
    Location {
        first_name: FIRST_NAME_BLEDAN,
        last_name: LAST_NAME_TABR,
        map_x: -8192,
        map_y: -63,
        map_offset: 0,
        appearance: 0x2d,
        troop_id: 0x37,
        status: 0b10000000,
        discoverable_at_phase: -1,
        field_c: 0,
        field_e: 0,
        spice_field_id: 0,
        spice_amount: 0,
        spice_density: 0xfa,
        field_13: 0,
        equipment: Equipment {
            harvesters: 0,
            ornithopters: 0,
            krys_knives: 2,
            laser_guns: 2,
            weirding_modules: 0,
            atomics: 0,
            bulbs: 0,
        },
        water: 0,
    },
    // [41] Bledan-Timin
    Location {
        first_name: FIRST_NAME_BLEDAN,
        last_name: LAST_NAME_TIMIN,
        map_x: -10013,
        map_y: -48,
        map_offset: 0,
        appearance: 0x2e,
        troop_id: 0x39,
        status: 0b10000000,
        discoverable_at_phase: -1,
        field_c: 0,
        field_e: 0,
        spice_field_id: 0,
        spice_amount: 0,
        spice_density: 0xb4,
        field_13: 0,
        equipment: Equipment {
            harvesters: 0,
            ornithopters: 0,
            krys_knives: 1,
            laser_guns: 1,
            weirding_modules: 0,
            atomics: 0,
            bulbs: 0,
        },
        water: 0,
    },
    // [42] Bledan-Tuek
    Location {
        first_name: FIRST_NAME_BLEDAN,
        last_name: LAST_NAME_TUEK,
        map_x: -21169,
        map_y: -61,
        map_offset: 0,
        appearance: 0x2f,
        troop_id: 0x3b,
        status: 0b10000000,
        discoverable_at_phase: -1,
        field_c: 0,
        field_e: 0,
        spice_field_id: 0,
        spice_amount: 0,
        spice_density: 0x78,
        field_13: 0,
        equipment: Equipment {
            harvesters: 0,
            ornithopters: 0,
            krys_knives: 1,
            laser_guns: 1,
            weirding_modules: 0,
            atomics: 0,
            bulbs: 0,
        },
        water: 0,
    },
    // [43] Bledan-Harg
    Location {
        first_name: FIRST_NAME_BLEDAN,
        last_name: LAST_NAME_HARG,
        map_x: -14996,
        map_y: -59,
        map_offset: 0,
        appearance: 0x28,
        troop_id: 0x3a,
        status: 0b10000000,
        discoverable_at_phase: -1,
        field_c: 0,
        field_e: 0,
        spice_field_id: 0,
        spice_amount: 0,
        spice_density: 0xc8,
        field_13: 0,
        equipment: Equipment {
            harvesters: 0,
            ornithopters: 0,
            krys_knives: 1,
            laser_guns: 1,
            weirding_modules: 0,
            atomics: 0,
            bulbs: 0,
        },
        water: 0,
    },
    // [44] Ergsun-Tabr
    Location {
        first_name: FIRST_NAME_ERGSUN,
        last_name: LAST_NAME_TABR,
        map_x: -18335,
        map_y: -36,
        map_offset: 0,
        appearance: 7,
        troop_id: 0x11,
        status: 0b10100000,
        discoverable_at_phase: 44,
        field_c: 0,
        field_e: 0,
        spice_field_id: 0,
        spice_amount: 0,
        spice_density: 0x96,
        field_13: 0,
        equipment: Equipment {
            harvesters: 1,
            ornithopters: 1,
            krys_knives: 0,
            laser_guns: 0,
            weirding_modules: 0,
            atomics: 0,
            bulbs: 0,
        },
        water: 0x50,
    },
    // [45] Ergsun-Timin
    Location {
        first_name: FIRST_NAME_ERGSUN,
        last_name: LAST_NAME_TIMIN,
        map_x: -15233,
        map_y: -24,
        map_offset: 0,
        appearance: 4,
        troop_id: 0x0f,
        status: 0b10000000,
        discoverable_at_phase: 40,
        field_c: 0,
        field_e: 0,
        spice_field_id: 0,
        spice_amount: 0,
        spice_density: 0x6e,
        field_13: 0,
        equipment: Equipment {
            harvesters: 0,
            ornithopters: 0,
            krys_knives: 1,
            laser_guns: 0,
            weirding_modules: 0,
            atomics: 0,
            bulbs: 0,
        },
        water: 0,
    },
    // [46] Ergsun-Tuek
    Location {
        first_name: FIRST_NAME_ERGSUN,
        last_name: LAST_NAME_TUEK,
        map_x: -27020,
        map_y: -34,
        map_offset: 0,
        appearance: 5,
        troop_id: 0x10,
        status: 0b10000000,
        discoverable_at_phase: 44,
        field_c: 0,
        field_e: 0,
        spice_field_id: 0,
        spice_amount: 0,
        spice_density: 0x3c,
        field_13: 0,
        equipment: Equipment {
            harvesters: 0,
            ornithopters: 0,
            krys_knives: 0,
            laser_guns: 0,
            weirding_modules: 0,
            atomics: 0,
            bulbs: 0,
        },
        water: 0,
    },
    // [47] Ergsun-Harg
    Location {
        first_name: FIRST_NAME_ERGSUN,
        last_name: LAST_NAME_HARG,
        map_x: -22586,
        map_y: -30,
        map_offset: 0,
        appearance: 6,
        troop_id: 0x12,
        status: 0b10000000,
        discoverable_at_phase: 44,
        field_c: 0,
        field_e: 0,
        spice_field_id: 0,
        spice_amount: 0,
        spice_density: 0xb4,
        field_13: 0,
        equipment: Equipment {
            harvesters: 1,
            ornithopters: 0,
            krys_knives: 1,
            laser_guns: 0,
            weirding_modules: 0,
            atomics: 0,
            bulbs: 0,
        },
        water: 0,
    },
    // [48] Ergsun-Clam
    Location {
        first_name: FIRST_NAME_ERGSUN,
        last_name: LAST_NAME_CLAM,
        map_x: -20112,
        map_y: -21,
        map_offset: 0,
        appearance: 1,
        troop_id: 0x0e,
        status: 0b10000000,
        discoverable_at_phase: 44,
        field_c: 0,
        field_e: 0,
        spice_field_id: 0,
        spice_amount: 0,
        spice_density: 0x96,
        field_13: 0,
        equipment: Equipment {
            harvesters: 0,
            ornithopters: 0,
            krys_knives: 1,
            laser_guns: 0,
            weirding_modules: 0,
            atomics: 0,
            bulbs: 0,
        },
        water: 0,
    },
    // [49] Ergsun-Tsymyn
    Location {
        first_name: FIRST_NAME_ERGSUN,
        last_name: LAST_NAME_TSYMYN,
        map_x: -21775,
        map_y: -43,
        map_offset: 0,
        appearance: 0,
        troop_id: 0,
        status: 0b10000000,
        discoverable_at_phase: 44,
        field_c: 0,
        field_e: 0,
        spice_field_id: 0,
        spice_amount: 0,
        spice_density: 0xa0,
        field_13: 0,
        equipment: Equipment {
            harvesters: 0,
            ornithopters: 0,
            krys_knives: 1,
            laser_guns: 0,
            weirding_modules: 0,
            atomics: 0,
            bulbs: 0,
        },
        water: 0,
    },
    // [50] Haga-Tabr
    Location {
        first_name: FIRST_NAME_HAGA,
        last_name: LAST_NAME_TABR,
        map_x: 27362,
        map_y: -15,
        map_offset: 0,
        appearance: 0x0b,
        troop_id: 0x13,
        status: 0b10100000,
        discoverable_at_phase: 90,
        field_c: 0,
        field_e: 0,
        spice_field_id: 0,
        spice_amount: 0,
        spice_density: 0xaa,
        field_13: 0,
        equipment: Equipment {
            harvesters: 0,
            ornithopters: 0,
            krys_knives: 1,
            laser_guns: 0,
            weirding_modules: 0,
            atomics: 0,
            bulbs: 0,
        },
        water: 0x28,
    },
    // [51] Haga-Timin
    Location {
        first_name: FIRST_NAME_HAGA,
        last_name: LAST_NAME_TIMIN,
        map_x: -31438,
        map_y: -10,
        map_offset: 0,
        appearance: 0x0a,
        troop_id: 0x14,
        status: 0b10100000,
        discoverable_at_phase: 90,
        field_c: 0,
        field_e: 0,
        spice_field_id: 0,
        spice_amount: 0,
        spice_density: 0xd2,
        field_13: 0,
        equipment: Equipment {
            harvesters: 0,
            ornithopters: 0,
            krys_knives: 0,
            laser_guns: 0,
            weirding_modules: 0,
            atomics: 0,
            bulbs: 0,
        },
        water: 0x0a,
    },
    // [52] Haga-Tuek
    Location {
        first_name: FIRST_NAME_HAGA,
        last_name: LAST_NAME_TUEK,
        map_x: 28672,
        map_y: -31,
        map_offset: 0,
        appearance: 0x29,
        troop_id: 0x42,
        status: 0b10000000,
        discoverable_at_phase: -1,
        field_c: 0,
        field_e: 0,
        spice_field_id: 0,
        spice_amount: 0,
        spice_density: 0xc3,
        field_13: 0,
        equipment: Equipment {
            harvesters: 1,
            ornithopters: 1,
            krys_knives: 0,
            laser_guns: 1,
            weirding_modules: 1,
            atomics: 0,
            bulbs: 0,
        },
        water: 0,
    },
    // [53] Haga-Harg
    Location {
        first_name: FIRST_NAME_HAGA,
        last_name: LAST_NAME_HARG,
        map_x: 23576,
        map_y: -38,
        map_offset: 0,
        appearance: 0x2a,
        troop_id: 0x3f,
        status: 0b10000000,
        discoverable_at_phase: -1,
        field_c: 0,
        field_e: 0,
        spice_field_id: 0,
        spice_amount: 0,
        spice_density: 0xf0,
        field_13: 0,
        equipment: Equipment {
            harvesters: 2,
            ornithopters: 2,
            krys_knives: 2,
            laser_guns: 2,
            weirding_modules: 2,
            atomics: 0,
            bulbs: 0,
        },
        water: 0,
    },
    // [54] Haga-Clam
    Location {
        first_name: FIRST_NAME_HAGA,
        last_name: LAST_NAME_CLAM,
        map_x: 26851,
        map_y: -48,
        map_offset: 0,
        appearance: 0x2b,
        troop_id: 0x3e,
        status: 0b10000000,
        discoverable_at_phase: -1,
        field_c: 0,
        field_e: 0,
        spice_field_id: 0,
        spice_amount: 0,
        spice_density: 0xc8,
        field_13: 0,
        equipment: Equipment {
            harvesters: 1,
            ornithopters: 1,
            krys_knives: 0,
            laser_guns: 1,
            weirding_modules: 1,
            atomics: 1,
            bulbs: 0,
        },
        water: 0,
    },
    // [55] Haga-Tsymyn
    Location {
        first_name: FIRST_NAME_HAGA,
        last_name: LAST_NAME_TSYMYN,
        map_x: 26388,
        map_y: -61,
        map_offset: 0,
        appearance: 0x2c,
        troop_id: 0x3d,
        status: 0b10000000,
        discoverable_at_phase: -1,
        field_c: 0,
        field_e: 0,
        spice_field_id: 0,
        spice_amount: 0,
        spice_density: 0xd2,
        field_13: 0,
        equipment: Equipment {
            harvesters: 2,
            ornithopters: 1,
            krys_knives: 1,
            laser_guns: 1,
            weirding_modules: 1,
            atomics: 1,
            bulbs: 0,
        },
        water: 0,
    },
    // [56] Haga-Siet
    Location {
        first_name: FIRST_NAME_HAGA,
        last_name: LAST_NAME_SIET,
        map_x: 31934,
        map_y: -59,
        map_offset: 0,
        appearance: 0x2d,
        troop_id: 0x3c,
        status: 0b10000000,
        discoverable_at_phase: -1,
        field_c: 0,
        field_e: 0,
        spice_field_id: 0,
        spice_amount: 0,
        spice_density: 0x32,
        field_13: 0,
        equipment: Equipment {
            harvesters: 1,
            ornithopters: 0,
            krys_knives: 0,
            laser_guns: 1,
            weirding_modules: 0,
            atomics: 0,
            bulbs: 0,
        },
        water: 0,
    },
    // [57] Haga-Pyons
    Location {
        first_name: FIRST_NAME_HAGA,
        last_name: LAST_NAME_PYONS,
        map_x: -32015,
        map_y: -35,
        map_offset: 0,
        appearance: 0x21,
        troop_id: 0,
        status: 0b10000000,
        discoverable_at_phase: 90,
        field_c: 0,
        field_e: 0,
        spice_field_id: 0,
        spice_amount: 0,
        spice_density: 0,
        field_13: 0,
        equipment: Equipment {
            harvesters: 0,
            ornithopters: 0,
            krys_knives: 0,
            laser_guns: 0,
            weirding_modules: 0,
            atomics: 0,
            bulbs: 0,
        },
        water: 0,
    },
    // [58] Cielago-Tabr
    Location {
        first_name: FIRST_NAME_CIELAGO,
        last_name: LAST_NAME_TABR,
        map_x: 30133,
        map_y: 5,
        map_offset: 0,
        appearance: 3,
        troop_id: 0,
        status: 0b10000000,
        discoverable_at_phase: 90,
        field_c: 0,
        field_e: 0,
        spice_field_id: 0,
        spice_amount: 0,
        spice_density: 0xe6,
        field_13: 0,
        equipment: Equipment {
            harvesters: 0,
            ornithopters: 0,
            krys_knives: 0,
            laser_guns: 0,
            weirding_modules: 0,
            atomics: 0,
            bulbs: 0,
        },
        water: 0,
    },
    // [59] Cielago-Timin
    Location {
        first_name: FIRST_NAME_CIELAGO,
        last_name: LAST_NAME_TIMIN,
        map_x: -27499,
        map_y: 2,
        map_offset: 0,
        appearance: 0x0d,
        troop_id: 0,
        status: 0b10100000,
        discoverable_at_phase: 90,
        field_c: 0,
        field_e: 0,
        spice_field_id: 0,
        spice_amount: 0,
        spice_density: 0xc8,
        field_13: 0,
        equipment: Equipment {
            harvesters: 0,
            ornithopters: 0,
            krys_knives: 0,
            laser_guns: 0,
            weirding_modules: 0,
            atomics: 0,
            bulbs: 0,
        },
        water: 0xa0,
    },
    // [60] Sihaya-Tabr
    Location {
        first_name: FIRST_NAME_SIHAYA,
        last_name: LAST_NAME_TABR,
        map_x: -28340,
        map_y: 24,
        map_offset: 0,
        appearance: 8,
        troop_id: 0x17,
        status: 0b10100000,
        discoverable_at_phase: 88,
        field_c: 0,
        field_e: 0,
        spice_field_id: 0,
        spice_amount: 0,
        spice_density: 0xaa,
        field_13: 0,
        equipment: Equipment {
            harvesters: 0,
            ornithopters: 0,
            krys_knives: 1,
            laser_guns: 0,
            weirding_modules: 0,
            atomics: 0,
            bulbs: 0,
        },
        water: 0x64,
    },
    // [61] Sihaya-Timin
    Location {
        first_name: FIRST_NAME_SIHAYA,
        last_name: LAST_NAME_TIMIN,
        map_x: -17165,
        map_y: 47,
        map_offset: 0,
        appearance: 0x0a,
        troop_id: 0x19,
        status: 0b10100000,
        discoverable_at_phase: 88,
        field_c: 0,
        field_e: 0,
        spice_field_id: 0,
        spice_amount: 0,
        spice_density: 0xc8,
        field_13: 0,
        equipment: Equipment {
            harvesters: 0,
            ornithopters: 0,
            krys_knives: 0,
            laser_guns: 0,
            weirding_modules: 0,
            atomics: 0,
            bulbs: 0,
        },
        water: 0xc8,
    },
    // [62] Sihaya-Tuek
    Location {
        first_name: FIRST_NAME_SIHAYA,
        last_name: LAST_NAME_TUEK,
        map_x: -14369,
        map_y: 22,
        map_offset: 0,
        appearance: 0x10,
        troop_id: 0,
        status: 0b10100000,
        discoverable_at_phase: 85,
        field_c: 0,
        field_e: 0,
        spice_field_id: 0,
        spice_amount: 0,
        spice_density: 0x8c,
        field_13: 0,
        equipment: Equipment {
            harvesters: 0,
            ornithopters: 0,
            krys_knives: 0,
            laser_guns: 0,
            weirding_modules: 0,
            atomics: 0,
            bulbs: 0,
        },
        water: 0x6e,
    },
    // [63] Sihaya-Harg
    Location {
        first_name: FIRST_NAME_SIHAYA,
        last_name: LAST_NAME_HARG,
        map_x: -17488,
        map_y: 31,
        map_offset: 0,
        appearance: 0x0b,
        troop_id: 0x18,
        status: 0b10100000,
        discoverable_at_phase: 88,
        field_c: 0,
        field_e: 0,
        spice_field_id: 0,
        spice_amount: 0,
        spice_density: 0xaa,
        field_13: 0,
        equipment: Equipment {
            harvesters: 0,
            ornithopters: 0,
            krys_knives: 0,
            laser_guns: 0,
            weirding_modules: 0,
            atomics: 0,
            bulbs: 0,
        },
        water: 0x69,
    },
    // [64] Sihaya-Clam
    Location {
        first_name: FIRST_NAME_SIHAYA,
        last_name: LAST_NAME_CLAM,
        map_x: -12578,
        map_y: -7,
        map_offset: 0,
        appearance: 3,
        troop_id: 0,
        status: 0b10100000,
        discoverable_at_phase: 40,
        field_c: 0,
        field_e: 0,
        spice_field_id: 0,
        spice_amount: 0,
        spice_density: 0x8c,
        field_13: 0,
        equipment: Equipment {
            harvesters: 0,
            ornithopters: 0,
            krys_knives: 0,
            laser_guns: 0,
            weirding_modules: 0,
            atomics: 0,
            bulbs: 0,
        },
        water: 0x78,
    },
    // [65] Sihaya-Pyons
    Location {
        first_name: FIRST_NAME_SIHAYA,
        last_name: LAST_NAME_PYONS,
        map_x: -19794,
        map_y: -11,
        map_offset: 0,
        appearance: 0x21,
        troop_id: 0,
        status: 0b10000000,
        discoverable_at_phase: 88,
        field_c: 0,
        field_e: 0,
        spice_field_id: 0,
        spice_amount: 0,
        spice_density: 0,
        field_13: 0,
        equipment: Equipment {
            harvesters: 0,
            ornithopters: 0,
            krys_knives: 0,
            laser_guns: 0,
            weirding_modules: 0,
            atomics: 0,
            bulbs: 0,
        },
        water: 0,
    },
    // [66] Celimyn-Tabr
    Location {
        first_name: FIRST_NAME_CELIMYN,
        last_name: LAST_NAME_TABR,
        map_x: 23990,
        map_y: 36,
        map_offset: 0,
        appearance: 0x0e,
        troop_id: 0x15,
        status: 0b10100000,
        discoverable_at_phase: 90,
        field_c: 0,
        field_e: 0,
        spice_field_id: 0,
        spice_amount: 0,
        spice_density: 0xaa,
        field_13: 0,
        equipment: Equipment {
            harvesters: 0,
            ornithopters: 0,
            krys_knives: 1,
            laser_guns: 0,
            weirding_modules: 0,
            atomics: 0,
            bulbs: 0,
        },
        water: 0x64,
    },
    // [67] Celimyn-Timin
    Location {
        first_name: FIRST_NAME_CELIMYN,
        last_name: LAST_NAME_TIMIN,
        map_x: 29075,
        map_y: 49,
        map_offset: 0,
        appearance: 0x0f,
        troop_id: 0x16,
        status: 0b10100000,
        discoverable_at_phase: 88,
        field_c: 0,
        field_e: 0,
        spice_field_id: 0,
        spice_amount: 0,
        spice_density: 0xf0,
        field_13: 0,
        equipment: Equipment {
            harvesters: 0,
            ornithopters: 0,
            krys_knives: 0,
            laser_guns: 0,
            weirding_modules: 0,
            atomics: 0,
            bulbs: 0,
        },
        water: 0xc8,
    },
    // [68] Celimyn-Tuek
    Location {
        first_name: FIRST_NAME_CELIMYN,
        last_name: LAST_NAME_TUEK,
        map_x: 16885,
        map_y: 39,
        map_offset: 0,
        appearance: 3,
        troop_id: 0,
        status: 0b10000000,
        discoverable_at_phase: -1,
        field_c: 0,
        field_e: 0,
        spice_field_id: 0,
        spice_amount: 0,
        spice_density: 0x8c,
        field_13: 0,
        equipment: Equipment {
            harvesters: 1,
            ornithopters: 1,
            krys_knives: 3,
            laser_guns: 0,
            weirding_modules: 0,
            atomics: 0,
            bulbs: 0,
        },
        water: 0,
    },
    // [69] Celimyn-Harg
    Location {
        first_name: FIRST_NAME_CELIMYN,
        last_name: LAST_NAME_HARG,
        map_x: -16384,
        map_y: 71,
        map_offset: 0,
        appearance: 0x0c,
        troop_id: 0x1a,
        status: 0b10100000,
        discoverable_at_phase: -1,
        field_c: 0,
        field_e: 0,
        spice_field_id: 0,
        spice_amount: 0,
        spice_density: 0xf0,
        field_13: 0,
        equipment: Equipment {
            harvesters: 0,
            ornithopters: 0,
            krys_knives: 2,
            laser_guns: 1,
            weirding_modules: 0,
            atomics: 0,
            bulbs: 0,
        },
        water: 0x96,
    },
];

impl GameState {
    // = seg000:5d36 location_is_Atreides_05d36 — carry set (true) when the
    // location is an Atreides holding: a city/village appearance (>= 0x28)
    // with status bit 8.
    pub(crate) fn location_is_atreides(&self, location_index: usize) -> bool {
        let loc = &self.locations[location_index];
        loc.appearance >= 0x28 && loc.status & 8 != 0
    }

    // = seg000:6231 get_location_type_string_offset — classify a location's
    // appearance byte into its type-string offset: 0 for the sietches
    // (< 0x20), 2 for 0x21..0x27, 3 for 0x28..0x2f, and 1 (the palaces) for
    // both 0x20 and >= 0x30.
    pub(crate) fn get_location_type_string_offset(&self, location_index: usize) -> u16 {
        // = seg000:6232 bl = [di+8] (appearance); 6235..624e the threshold
        //   ladder (the >= 0x30 tail lands on 3 - 2 = 1).
        match self.locations[location_index].appearance {
            0x00..0x20 => 0,
            0x20 => 1,
            0x21..0x28 => 2,
            0x28..0x30 => 3,
            _ => 1,
        }
    }

    // = seg000:629d draw_string_location_type — draw the location's type
    // string ("Sietch: ", "Palace: ", ...) at (x, y) with the given colour
    // word.
    pub(crate) fn draw_string_location_type(
        &mut self,
        location_index: usize,
        color: u16,
        x: u16,
        y: u16,
    ) {
        // = seg000:629d call get_location_type_string_offset; 62a0 add
        //   ax,44h; 62a3 jmp font_draw_phrase_or_command_string_with_color_
        //   at_pos.
        let index = self.get_location_type_string_offset(location_index) + 0x44;
        self.font_draw_phrase_or_command_string_with_color_at_pos(index, color, x, y);
    }

    // = seg000:62a6 draw_location_name — draw a location's two-part name
    // ("Tuono-Tabr") at (x, y) with the given colour word: the first-name
    // string, a separator (a space before the house last names Atreides/
    // Harkonnen, '-' before the sietch last names), then the last-name string
    // (COMMAND entries 0xc + last_name).
    pub(crate) fn draw_location_name(&mut self, location_index: usize, color: u16, x: u16, y: u16) {
        let (first, last) = {
            let loc = &self.locations[location_index];
            (loc.first_name, loc.last_name)
        };
        // = seg000:62a6 al = [di] (first_name); 62aa add ax,0; 62ad call
        //   font_draw_phrase_or_command_string_with_color_at_pos.
        self.font_draw_phrase_or_command_string_with_color_at_pos(first as u16, color, x, y);
        // = seg000:62b0 cmp byte ptr [di+1],3; 62b4/62b8 al = ' ' when the
        //   last name is below 3 (Atreides/Harkonnen), else '-'; 62ba the
        //   glyph func.
        self.font_draw_glyph(if last < 3 { 0x20 } else { 0x2d });
        // = seg000:62be al = [di+1] (last_name); 62c3 add ax,0ch; 62c6 jmp
        //   font_draw_phrase_or_command_string.
        self.font_draw_phrase_or_command_string(last as u16 + 0xc);
    }
}
